use academy;
select * from `curators`;
select * from `departments`;
select * from `faculties`;
select * from `groups`;
select * from `groups_curators`;
select * from `groups_lectures`;
select * from `groups_students`;
select * from `lectures`;
select * from `students`;
select * from `subjects`;
select * from `teachers`;